#!/bin/bash
curl http://localhost:3000/health;
curl http://localhost:3000/health;
curl http://localhost:3000/time;
curl http://localhost:3000/time;
curl http://localhost:3000/time;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"operation": "add", "a": 12, "b": 30}' http://localhost:3000/calculate;
curl --json '{"operation": "subtract", "a": 72, "b": 30}' http://localhost:3000/calculate;
curl --json '{"operation": "multiply", "a": 21, "b": 2}' http://localhost:3000/calculate;
curl --json '{"operation": "divide", "a": 1050, "b": 25}' http://localhost:3000/calculate;
curl --json '{"operation": "modulo", "a": 10042, "b": 100}' http://localhost:3000/calculate;
curl http://localhost:3000/health;
curl http://localhost:3000/health;
curl http://localhost:3000/time;
curl http://localhost:3000/time;
curl http://localhost:3000/time;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"operation": "add", "a": 12, "b": 30}' http://localhost:3000/calculate;
curl --json '{"operation": "subtract", "a": 72, "b": 30}' http://localhost:3000/calculate;
curl --json '{"operation": "multiply", "a": 21, "b": 2}' http://localhost:3000/calculate;
curl --json '{"operation": "divide", "a": 1050, "b": 25}' http://localhost:3000/calculate;
curl --json '{"operation": "modulo", "a": 10042, "b": 100}' http://localhost:3000/calculate;
curl http://localhost:3000/health;
curl http://localhost:3000/health;
curl http://localhost:3000/time;
curl http://localhost:3000/time;
curl http://localhost:3000/time;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"answer": "42, Earthling!"}' http://localhost:3000/echo;
curl --json '{"operation": "add", "a": 12, "b": 30}' http://localhost:3000/calculate;
curl --json '{"operation": "subtract", "a": 72, "b": 30}' http://localhost:3000/calculate;
curl --json '{"operation": "multiply", "a": 21, "b": 2}' http://localhost:3000/calculate;
curl --json '{"operation": "divide", "a": 1050, "b": 25}' http://localhost:3000/calculate;
curl --json '{"operation": "modulo", "a": 10042, "b": 100}' http://localhost:3000/calculate;
curl http://localhost:3000/requests;
curl http://localhost:3000/requests;
curl http://localhost:3000/requests;
curl http://localhost:3000/requests;
curl http://localhost:3000/requests;
curl http://localhost:3000/requests;
curl http://localhost:3000/requests;
curl http://localhost:3000/requests
